### ISSUE TITLE
targetSdkVersion

### ISSUE THREAD

**Issue by Xlythe** [moritz-wundke/android-page-curl#1]
Can't set targetSdkVersion to be higher than "13" in the Android Manifest. If you do, about halfway through the curl it starts showing the background on top of the foreground.

**Comment by zhaoyouqi** [comment]
Is there any solution to fix this issue with higher sdk version?

**Comment by moritz-wundke** [comment]
You should adapt the code, I think the way android creates the paths
changed after API 13.

On Mon, May 5, 2014 at 11:09 AM, qq157755587 notifications@github.com
wrote:

> Is there any solution to fix this issue with higher sdk version?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/MysticTreeGames/android-page-curl/issues/1#issuecomment-42170368
> .

## 

_Moritz Wundke_
www.MysticTreeGames.com
www.DarkCultureGames.com http://www.darkculturegames.com/

**Comment by nilesh2008s** [comment]
id doesnt show any thing how would be used in android studio

**Comment by moritz-wundke** [comment]
It's an old eclipse project so you might just need to convert or import it.
