### ISSUE TITLE
Where are he styles?

### ISSUE THREAD

**Issue by Kharlos** [moritz-wundke/android-page-curl#14]
well i clone the project but it dont have any of styles insade

TypedArray a = context.obtainStyledAttributes(attrs, R.styleable.PageCurlView);
	
			// Get data
			bEnableDebugMode = a.getBoolean(R.styleable.PageCurlView_enableDebugMode, bEnableDebugMode);
			mCurlSpeed = a.getInt(R.styleable.PageCurlView_curlSpeed, mCurlSpeed);
			mUpdateRate = a.getInt(R.styleable.PageCurlView_updateRate, mUpdateRate);
			mInitialEdgeOffset = a.getInt(R.styleable.PageCurlView_initialEdgeOffset, mInitialEdgeOffset);
			mCurlMode = a.getInt(R.styleable.PageCurlView_curlMode, mCurlMode);
wher are those styles?

**Comment by moritz-wundke** [comment]
They are here => https://github.com/moritz-wundke/android-page-curl/blob/master/res/values/attrs.xml
