### ISSUE TITLE
Question about flipping

### ISSUE THREAD

**Issue by Yok86** [moritz-wundke/android-page-curl#4]
Hi!

I really like your work and would like to use it, but I can't figure out, how can I turn off flipping when I just touch the screen.
Is it possible somehow?

I thought I do a book like app, but it's not good that when I just touch the screen it flips.
I rather want to use it like I start pulling the view and when it is over the half or quarter of the views width, then it flips automatically.

I really appreciate any help you can provide.

**Comment by DiamondSoftware** [comment]
Good question. I am working on a similar problem over the next few months.
I will share when/if I solve this in an elegant way.
