### ISSUE TITLE
not upload more than 20pages..

### ISSUE THREAD

**Issue by aashish2013** [moritz-wundke/android-page-curl#6]

**Comment by moritz-wundke** [comment]
Take in mind that this is just a concept, to show the math behind it, it is
quite less effective than a production ready view. To be able to handle
infinite pages, you should cache and lazy-load them.

On Thu, Dec 26, 2013 at 2:29 PM, aashish2013 notifications@github.comwrote:

> —
> Reply to this email directly or view it on GitHubhttps://github.com/MysticTreeGames/android-page-curl/issues/6
> .

## 

_Moritz Wundke_
www.MysticTreeGames.com
www.DarkCultureGames.com http://www.darkculturegames.com/
