### ISSUE TITLE
About  TXT  File

### ISSUE THREAD

**Issue by Just-D** [moritz-wundke/android-page-curl#7]
How can i add a TXT  file to this ??? I want to make an E-Book ,use this great Effect !!!

**Comment by moritz-wundke** [comment]
Hi,

you could check this opensource implementation of an e-book reader that
uses the curl effect as an animation component:
http://www.pageturner-reader.org/

Cheers,
Moss

On Wed, Feb 26, 2014 at 3:42 AM, Just-D notifications@github.com wrote:

> How can i add a TXT file to this ??? I want to make an E-Book ,use this
> great Effect !!!
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/MysticTreeGames/android-page-curl/issues/7
> .

## 

_Moritz Wundke_
www.MysticTreeGames.com
www.DarkCultureGames.com http://www.darkculturegames.com/
